<% user = ENV.key?("MYSQL_ROOT_PASSWORD") ? "root" : ENV["MYSQL_USER"] %>
<% password = ENV.key?("MYSQL_ROOT_PASSWORD") ? ENV["MYSQL_ROOT_PASSWORD"] : ENV["MYSQL_PASSWORD"] %>

# ==============================================================================
default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["MYSQL_MAX_CONNECTIONS"] || 5 %>
  username: <%= user || 'root' %>
  password: <%= password || 'password' %>
  host: <%= ENV["DATABASE_SERVICE_NAME"] || '127.0.0.1' %>
  port: 3306
  database: <%= ENV['MYSQL_DATABASE'] %>

# ==============================================================================
development:
  <<: *default
  database: redmine_development

# ==============================================================================
test:
  <<: *default
  database: redmine_test

# ==============================================================================
production:
  <<: *default
